### ISSUE TITLE
values.yaml points to old Elastic version 6.8.5

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/zeebe-cluster-helm#115]
Zeebe 1.0.x [requires](https://docs.camunda.io/docs/reference/supported-environments/#zeebe) at least Elasticsearch 7.12.x

https://github.com/camunda-community-hub/zeebe-cluster-helm/blob/a046afcd97bdccca03cfe8790afe5c7cfd844a28/charts/zeebe-cluster-helm/values.yaml#L38

**Comment by Zelldon** [comment]
thanks @falko yeah we have to fix this

**Comment by nitram509** [comment]
Cross-linking: this seems to be a duplicate #114

**Comment by falko** [comment]
I knew I had seen this before. Just couldn't find it ;-)
