### ISSUE TITLE
Add support for Hazelcast exporter mounted with Env variables

### ISSUE THREAD

**Issue by salaboy** [camunda-community-hub/zeebe-cluster-helm#24]
Add out of the box support for Hazelcast exporter to the chart.

**Comment by Zelldon** [comment]
This would be awesome :+1:

**Comment by salaboy** [comment]
reference in docker compose: https://github.com/zeebe-io/zeebe-docker-compose/commit/40d542f48a8e6cbedbcbf2f7f653beb59191eb0b#diff-c3983ba33a282ce008cfd4c9e73f1c2b

**Comment by Zelldon** [comment]
I also added a dockerfile in the hazelcast exporter repo https://github.com/zeebe-io/zeebe-hazelcast-exporter/blob/master/Dockerfile

**Comment by salaboy** [comment]
@Zelldon yeah.. but the whole point of this is to use the official images right?

**Comment by salaboy** [comment]
@Zelldon is that docker image being published -> https://github.com/zeebe-io/zeebe-hazelcast-exporter/blob/master/Dockerfile ? 

this fix in the chart should enable other exporters to be registered.. we should avoid publishing tons of different docker images with different exporters

**Comment by Zelldon** [comment]
https://hub.docker.com/r/zelldon/zeebe-hazelcast I need that for testing

**Comment by salaboy** [comment]
@Zelldon yeah.. but I cannot use your image for the public charts.. also .. for test containers you should be able to mount the jar as @jwulf is doing ..

**Comment by Zelldon** [comment]
> @Zelldon yeah.. but I cannot use your image for the public charts.

This is fine, was just saying how I do it now.

> for test containers you should be able to mount the jar as @jwulf is doing ..

Sure I can do that but this is not convenient. I would need in my C# integration tests download the jar from somewhere, copy it somewhere then mount it via test containers instead of just referencing an image which contains the thing :sweat_smile:

**Comment by ChrisKujawa** [comment]
It is done in zeeqs so I assume we found a solution
